// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleApp.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public string Name { get; set; }

    public int StockLevel { get; set; }
}