// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace InventoryTransactionsApp.Models;

public partial class Transaction
{
    public int TransactionId { get; set; }

    public int ProductId { get; set; }

    [Column("TransactionType")]
    public TransactionType Type { get; set; }

    public int Quantity { get; set; }

    public DateTime Date { get; set; }

    public virtual Product Product { get; set; }

    public enum TransactionType
    {
        Add,
        Remove
    }

}